DROP TABLE POSTER;
DROP TABLE ACTED_IN;
DROP TABLE MOVIE;
DROP TABLE DIRECTOR;
DROP TABLE REVIEW;
DROP TABLE ACTOR;
DELETE FROM PASSWORD WHERE UID > 3;
DELETE FROM ADMIN WHERE UID > 1;
DELETE FROM USER WHERE UID > 3;

CREATE TABLE POSTER (
  MID INTEGER NOT NULL,
  img TEXT    NOT NULL,
  UID INTEGER NOT NULL,
  PRIMARY KEY (MID),
  FOREIGN KEY (MID) REFERENCES MOVIE (MID),
  FOREIGN KEY (UID) REFERENCES ADMIN (UID)
);

CREATE TABLE DIRECTOR (
  UID            INTEGER PRIMARY KEY,
  famous_for_MID INTEGER,
  given_name     TEXT    NOT NULL,
  DoB            INTEGER,
  FOREIGN KEY (UID) REFERENCES USER (UID)
);

CREATE TABLE MOVIE (
  MID          INTEGER PRIMARY KEY,
  director_UID INTEGER,
  title        TEXT    NOT NULL,
  release_date INTEGER,
  entered_by   INTEGER NOT NULL,
  entered_date INTEGER NOT NULL,
  FOREIGN KEY (director_UID) REFERENCES DIRECTOR (UID),
  FOREIGN KEY (entered_by) REFERENCES ADMIN (UID)
);

CREATE TABLE REVIEW (
  MID          INTEGER NOT NULL,
  UID          INTEGER NOT NULL,
  text         TEXT    NOT NULL,
  rating       INTEGER NOT NULL,
  created_date INTEGER NOT NULL,
  PRIMARY KEY (MID, UID),
  FOREIGN KEY (MID) REFERENCES MOVIE (MID),
  FOREIGN KEY (UID) REFERENCES USER (UID)
);

CREATE TABLE ACTOR (
  UID        INTEGER PRIMARY KEY,
  stage_name TEXT,
  given_name TEXT    NOT NULL,
  DoB        INTEGER,
  FOREIGN KEY (UID) REFERENCES USER (UID)
);

CREATE TABLE ACTED_IN (
  MID            INTEGER NOT NULL,
  UID            INTEGER NOT NULL,
  character_role TEXT    NOT NULL,
  PRIMARY KEY (MID, UID),
  FOREIGN KEY (MID) REFERENCES MOVIE (MID),
  FOREIGN KEY (UID) REFERENCES USER (UID)
);
